### ISSUE TITLE
BUG: Adding unbreaking 1 to every vanilla enchant

### ISSUE THREAD

**Issue by Dylanlay02PvP** [Zedly/Zenchantments#41] opened 2020-07-07 20:07 UTC
![image](https://user-images.githubusercontent.com/12952778/86836456-2697cf80-c063-11ea-990b-018f07143757.png)
![image](https://user-images.githubusercontent.com/12952778/86836490-31526480-c063-11ea-9b81-2f1cb6f7011d.png)
Hello so when in an anvil every enchantment book gets "unbreaking:0" then adds unbreaking 1 to the final product. Im not sure how to change this it would be much appreciated if you could tell me how to turn off the "unbreaking:0" thing.

**Comment by Geolykt** [comment] 2020-07-08 08:35
Duplicate of #40

**Comment by Dylanlay02PvP** [comment] 2020-07-09 17:54
> Duplicate of #40

I read the other reports Is there anyway I can just completely disable the unbreaking thing instead of trying to modify it and make it work?

**Comment by Geolykt** [comment] 2020-07-09 17:56
no

**Comment by Dylanlay02PvP** [comment] 2020-07-09 19:20
> no, not without editing the source/byte code

Will there ever be a patch for 1.15.2

**Comment by Geolykt** [comment] 2020-07-09 20:28
> 
> 
> > no, not without editing the source/byte code
> 
> Will there ever be a patch for 1.15.2

It could, but I think supporting 1.16.1 is more important of a task

**Comment by Zedly** [comment] 2023-02-27 17:59
Accidental adding of Unbreaking I has been mitigated

**Closed by Zedly** 2023-02-27 17:59 UTC
